carreira/carreira/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

carreira/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('',views.cadastro, name='cadastro'),
    path('listar',views.listar, name='listar')
]

carreira/core/models.py
from django.db import models
from django.utils import timezone

class CadastroModel(models.Model):
    selecionar_professor = (
        ('Orlando', 'ORLANDO SARAIVA JR'),
        ('Nilton', 'NILTON SACCO'),
        ('Joao', 'JOAO NETO'),
    )

    nome = models.CharField('nome',max_length=100)
    professor = models.CharField('professor',max_length=100, choices=selecionar_professor, default='Orlando')
    data = models.DateField(verbose_name='Data',default=timezone.now())

    def __str__(self):
        return self.nome
    
    class Meta:
        verbose_name_plural = 'Aluno'

carreira/core/forms.py
from django import forms
from .models import CadastroModel
from django.forms import ModelForm

class CadastroForm(ModelForm):

    class Meta:
        model = CadastroModel
        fields = ['nome','professor']
        error_messages = {
        'nome': {
            'required': ("Informe o nome da atividade."),
        }
    }

    def clean_nome(self):
        nome = self.cleaned_data['nome']
        return nome

    def clean(self):
        self.cleaned_data = super().clean()
        return self.cleaned_data

carreira/core/views.py
from django.shortcuts import render
from .models import CadastroModel
from .forms import CadastroForm

def cadastro(request):
    if request.method == 'POST':
        form = CadastroForm(request.POST)

        if form.is_valid():
            CadastroModel.objects.create(**form.cleaned_data)
            contexto = {
                'cadastro': True
            }
            return render(request, "cadastro.html", contexto)
        else:
            contexto = {'form': form}
            return render(request, "cadastro.html", contexto)
    else:
        contexto = {'form': CadastroForm}
        return render(request, "cadastro.html", contexto)

def listar(request):
    cadastrados = CadastroModel.objects.all() 
    if len(cadastrados)>0:
        contexto = {
            'cadastrados': cadastrados
        }
        return render(request, 'listar.html', contexto)
    else:
        contexto = {
            'cadastrados': False
        }
        return render(request, 'listar.html', contexto)

carreira/core/templates/cadastro.html
{% load static %}
<!DOCTYPE html>
<html lang="pt_br">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Atividades</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    </head>
    <body>
        <main class="container-fluid p-5 d-flex justify-content-center align-items-center">
            <div>
                <form action={% url 'core:cadastro' %} novalidate method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <h1 class="d-flex justify-content-center p-5 pt-0">Cadastrar Presença</h1>
                    <h5>Nome da aluno: {{ form.nome }}</h5>
                    <br>
                    <h5>Nome do professor: {{ form.professor }}</h5>
                    <br>
                    <div class="text-center">
                        <input type="submit" value="Cadastrar" class="btn btn-primary">
                    </div>
                </form>
            </div>
        </main>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
    </body>
</html>

carreira/core/templates/listar.html
{% load static %}
<!DOCTYPE html>
<html lang="pt_br">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Cadastros</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    </head>
    <body>
        <main class="container-fluid p-5">
            {% if cadastrados %}
            <h1 class="d-flex justify-content-center p-5 pt-0">Alunos ja cadastrados</h1>
            <table class="table table-striped table-hover">
            <thead>
                <tr>
                <th>Aluno</th>
                <th>Professor</th>
                <th>Data</th>
                </tr>
            </thead>
            <tbody>
                {% for cadastros in cadastrados %}
                <tr>
                <td>{{ cadastros.nome }}</td>
                <td>{{ cadastros.professor }}</td>
                <td>{{ cadastros.data }}</td>
                </tr>
                {% endfor %}
            </tbody>
            </table>
            {% else %}
            <h1 class="d-flex justify-content-center p-5 pt-0">Não há alunos cadastrados!</h1>
            {% endif %}
        
        </main>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
    </body>
</html>